### ISSUE TITLE
Implement the hashtagging in the url to allow bookmarkable steps 

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/iguides-common#13]
We should allow users to be able to bookmark a step other than the first step.  Right now, user always have to start from the first step when they come to the circuit breaker guide.

**Comment by dmorgant** [comment]
All steps have a name element, which is currently used to identify the step internally. The step title element is what gets printed. We now need a step identifier value which can be used as the hash value in a URL to point directly to the indicated step.

For the step identifier element to be used as the hash value to the step, we will convert the title as they do in the static guides. Each space, apostrophe, and colon will be changed to a dash. We decided to go with a new step element (identifier) because in that way last minute changes to the TOC titles will not affect any logic previously written for the step. See OpenLiberty/iguides-common#13 for more information on 'Implement the hashtagging in the url to allow bookmarkable steps'.

The URL hashtags for the static guides are lower case hyphen (dash) separated values, like:
https://openliberty.io/guides/rest-client-java.html#what-you-ll-learn or
https://openliberty.io/guides/rest-client-java.html#contribute-to-this-guide

**Comment by dmorgant** [comment]
Implementation:

All steps have a step title which is what gets printed in the table of contents (TOC). Steps also have a name element, which is used to identify the step internally.   Sections, which appear as part of a Step page, also have both a step title and a step name.  Sections appear in the TOC, but you can't directly navigate to their section of the page via next and previous buttons since they are only part of a page.  We will enable bookmarking for both steps and sections.  

The step's names are stored in the orderedStepNamesArray in table-of-contents.js, which is used in navigating guide pages via previous and next.   Therefore, this array does not store section names.  We need another element to track hashes for each step and section title.  I created a hashStepNames object in step-content.js which will be used to track the hash names for both steps and sections with their step/section name.  This object will be initialized when the steps are originally created in step-content.js.  The algorithm for creating the hash will also be defined in  __createStepHashIdentifier in step-content.js.

In blueprint.js, I added a window.onhashchange function for detecting changes in the hash value of the URL.  Code from stepContent.js will then be invoked to create and show the correct page based on the hash value.  This will involve selecting the corresponding step in the TOC and, when the hash points to a section rather than a step, scrolling to the beginning of the section.

As steps or sections are selected in the TOC, or the next/previous buttons are selected,  the hash value in the URL will be updated so that a user can select to bookmark any particular page within the guide.
