### ISSUE TITLE
 New table of content style

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/iguides-common#147]
![image.png](https://images.zenhubusercontent.com/59d7b56bb0222d5de47a9368/f9c4565c-5a62-4521-91ab-affbb483b114)

**Comment by steven1046** [comment]
The table-of-contents.css can be leveraged from the static multipane layout.

**Comment by dmorgant** [comment]
Initial drop of code to enable the multipane layout with the new TOC for the interactive guides was done with OpenLiberty/openliberty.io#363.

It appears that we will be able to use the styling in openliberty.io table-of-contents.css.   To see this, when you enable an interactive guide to use the iguide-multipane layout, you must also remove 
'interactive-guides/table-of-contents' from the guide's .html file under the CSS section.

Some of the additional items to work on include:
-  Remove the 'Great work! You're done!', 'Contribute to this page', and 'Related guides' steps from each interactive guide's JSON file as these steps will now be covered in the End of Guide section that appears at the very bottom of each guide (not contained in the CSS).   We need to determine what has to be done to set up this section for each of our guides including adding categories and related links.  

- The selected step in the guide does not remain highlighted.   Steven and I believe this is because the guide does not yet load ALL of its steps.  So we will continue to test after completing that work.
