### ISSUE TITLE
Implement the tabbing sequence for the multipane guide design

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguides-common#186]
Implement the tabbing sequence for the multipane guide design when in three column mode.   

The tabbing should go from
- URL bar
- Guide header - across menu items
- Across the breadcrumbs
- Down through the TOC entries
- Through the Tags
- To the top of the #guide_content - the guide meta
- Through the sections stopping at all headers and tabbable portions within each (links, instructions, buttons, whatever)
    - At the bottom of each section, tabbing should go to the widgets in the right column (#code_column) for that section. Then at the bottom of the last widget for the section, tabbing should go to the header for the next section in the guide_content column which should trigger the widgets to change in the right column.  (Should we tab into greyed out (disabled) widgets in the right column?)
- At the end of the last section, tabbing should go to the End-of-guide content.

**Comment by steven1046** [comment]
Should we allow tabbing to the code snippet copy buttons on the left side? Currently, the design has the copy appear on hover. They can tab to the copy button on the right side where it has the full code file so they can still copy the code.

**Comment by steven1046** [comment]
Things not fixed by https://github.com/OpenLiberty/openliberty.io/pull/754:
- [ ] In interactive guides, tabbing backwards from a section header (<h2> element), the page is scrolled back to show the header of the previous element, but the activeElement is the <body> element, not the last widget in the #code_column as expected. If you then tab forward, you end up within the 'Nice work! You did it!' section at the bottom of the guide.
- [ ] The #code_column needs some sort of label added to it if we are going to stop there. Just remember that it needs to make sense in single-column mode too or not be read there.
- [ ] In static guides, when you tab to #code_column, the whole column is read as one HUGE sentence. For example, "System application dot java copy file contents package io dot open liberty dot guides dot rest semi-colon import javax dot ws dot ..........." It is not clear that we are reading through the contents of a file.
- [ ] In interactive guides, when you tab to #code_column, it summarizes the contents as one HUGE sentence. For example on a 2-widget step it says "Sample browser window tabbed container for file editor". On a 3-widget step it says "Sample browser window check balance microservice with circuit breaker check balance microservice tabbed container for file editor".
- [ ] In static guides, as you tab from the #code_column's copy file contents button, you hear 'Raise an issue link' and then it reads the next header. Not sure why that happens, but it is confusing.

**Comment by steven1046** [comment]
**Single column view only**
- [ ] When tabbing forward and you press enter on the TOC, it should open it up and put focus in the TOC.
- [ ] When tabbing through the TOC forwards, and you reach the end, send focus back to the TOC hamburger so they can close it.

**Comment by steven1046** [comment]
Closing this issue since the code changes are in the openliberty.io repo.
